language: java
jdk:
  - openjdk8

branches:
  only:
    - master

#      Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_install:
  - chmod +x gradlew

# CI 완료 시 메일 알람
notifications:
  email:
    recipients:
      - "jylim@bsks.ac.kr"

before_deploy:
  - mkdir -p before-deploy # zip에 포함시킬 파일들을 담을 DIR 생성
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy * # before-deploy로 이동 후 전체 압축
  - cd ../ && mkdir -p deploy # 상위 디랙토리 이동 후 deploy 디렉토리 생성
  - mv before-deploy/before-deploy.zip deploy/spring-boot-project.zip # deploy로 zip 파일 이동

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # travis에서 설정된 변수
    secret_access_key: $AWS_SECRET_KEY # travis에서 설정된 변수

    bucket: spring-boot-project-build # s3 버킷 명
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 접근 private

    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # travis에서 설정된 변수
    secret_access_key: $AWS_SECRET_KEY # travis에서 설정된 변수

    bucket: spring-boot-project-build # s3 버킷 명
    key: spring-boot-project.zip # 빌드파일 압축해서 전달

    bundle_type: zip # 압축 확장자
    application: spring-boot-project #웹 콘솔에서 등록한 codeDeploy 앱 이름

    deployment_group: spring-boot-project-group # 웹 콘솔에서 등록한 codeDeploy 배포 그룹 이름

    region: ap-northeast-2
    wait-until-deployed: true
